Repository spaceship-prompt/spaceship-prompt, pull requests merged in 2018-03, with the labels that each got.

#385 Fix directory truncation in git repositories with symlinks in path
  sections/dir.zsh
Labels: bug, improvement

#387 Show complete go version instead of first two digits
  sections/golang.zsh
Labels: improvement

#219 Print GHC version instead of stack version
  README.md
  sections/haskell.zsh
Labels: improvement

#363 Show added git status when staged file is modified
  sections/git_status.zsh
Labels: improvement

#398 Fix dir truncation for .git repo and subdirs
  sections/dir.zsh
Labels: improvement

#402 Reduce number of commands used to get go version
  sections/golang.zsh
Labels: improvement

#403 Allow symbols for virtualenv sections
  docs/Options.md
  sections/venv.zsh
Labels: new-feature

#390 Escape comments while checking duplicate prompt installation
  scripts/install.sh
Labels: improvement
