Repository spaceship-prompt/spaceship-prompt, pull requests merged in 2018-02, with the labels that each got.

#372 add installation instructions for arch linux (from user repository)
  README.md
Labels: docs, improvement

#381 Update issue template with duplicates and Troubleshooting
  .github/ISSUE_TEMPLATE.md
Labels: docs

#309 Detect composer.json for php
  docs/Options.md
  sections/php.zsh
Labels: improvement
