Repository spaceship-prompt/spaceship-prompt, pull requests merged in 2018-05, with the labels that each got.

#435 Document handling of package version not found
  docs/Options.md
Labels: docs

#438 Fix typo in package version doc
  docs/Options.md
Labels: docs

#437 Change `grep --colour` to `grep --color`
  sections/julia.zsh
  sections/rust.zsh
Labels: improvement

#432 Add space after kubecontext symbol
  sections/kubecontext.zsh
Labels: improvement

#447 Show all indicators for hg status
  sections/hg_status.zsh
Labels: bug
