Repository spaceship-prompt/spaceship-prompt, pull requests merged in 2018-11, with the labels that each got.

#533 Remove argument from char test shebang
  tests/char.test.zsh
Labels: bug

#517 Add image for powerline dir lock symbol
  docs/Options.md
Labels: docs

#548 Fix orderd list counnt on CONTRIBUTING page
  CONTRIBUTING.md
Labels: docs

#550 Recognize pyproject.toml when showing pyenv section
  sections/pyenv.zsh
Labels: improvement

#559 Fix bug and support go modules since go v1.11
  sections/golang.zsh
Labels: improvement

#549 Fix "bad math expression" for battery with UPS
  sections/battery.zsh
Labels: improvement, review-required

#541 acpi should take precedence in battery
  sections/battery.zsh
Labels: improvement, review-required

#467 README: add additional prompt to switch font to powerline
  README.md
Labels: docs, improvement

#534 Group and quote local variable declaration
  sections/char.zsh
Labels: improvement, review-required

#417 Fix directory truncation inside .git dir
  lib/utils.zsh
Labels: improvement

#565 Add namespace to k8s section
  sections/kubecontext.zsh
Labels: improvement, new-feature, review-required

#544 Use Zsh field splitting instead of awk
  sections/docker.zsh
  sections/ruby.zsh
Labels: improvement

#566 Document kubecontext showing namepace
  docs/Options.md
Labels: docs, improvement

#395 Support for several filenames in COMPOSE_FILE
  docs/Options.md
  sections/docker.zsh
Labels: improvement

#431 Dropping pyenv in favor of python section
  README.md
  docs/API.md
  docs/Options.md
  docs/README.md
  docs/Troubleshooting.md
  sections/pyenv.zsh
  sections/python.zsh
  spaceship.zsh
Labels: breaking, improvement

#571 Add spacefish to "Related Projects"
  README.md
Labels: docs

#575 Kubernetes namespace display can be turned off
  docs/Options.md
  sections/kubecontext.zsh
Labels: improvement
