Repository spaceship-prompt/spaceship-prompt, pull requests merged in 2018-07, with the labels that each got.

#281 Add SPACESHIP_DIR_TRUNC_PREFIX, a prefix before cwd when truncated
  docs/Options.md
  sections/dir.zsh
Labels: new-feature, proposal

#482 fix typo
  README.md
Labels: docs

#475 Link to Troubleshooting from bug issue template
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
Labels: docs, improvement

#483 Fix npm script `test` error
  package.json
Labels: bug

#445 fix issue when the # of jobs is greater than 1
  sections/jobs.zsh
Labels: bug

#421 modify declaration of dir variable in sections/dir
  docs/API.md
  sections/char.zsh
  sections/dir.zsh
  sections/elixir.zsh
  sections/node.zsh
  sections/ruby.zsh
  sections/swift.zsh
  sections/time.zsh
  sections/user.zsh
  sections/venv.zsh
  sections/xcode.zsh
Labels: improvement

#486 Add SPACESHIP_JOBS_AMOUNT_THRESHOLD variable
  docs/Options.md
  sections/jobs.zsh
Labels: improvement

#489 Document jobs amount prefix and suffix
  docs/Options.md
Labels: docs
