Repository spaceship-prompt/spaceship-prompt, pull requests merged in 2018-10, with the labels that each got.

#520 Let's use cut instead of grep!
  sections/rust.zsh
Labels: improvement

#522 Use AWS_PROFILE variable for aws named profiles
  docs/Options.md
  sections/aws.zsh
Labels: improvement, review-required

#528 Add Elm Section
  README.md
  docs/Options.md
  docs/README.md
  sections/elm.zsh
  spaceship.zsh
  tests/elm.test.zsh
  tests/stubs/elm
Labels: new-feature

#532 Spellcheck Docs
  README.md
  docs/API.md
  docs/Options.md
  docs/Troubleshooting.md
  lib/utils.zsh
Labels: docs

#461 Add options to change secondary and/or root prompt chars
  docs/Options.md
  sections/char.zsh
  spaceship.zsh
Labels: new-feature, under-discussion

#539 Minor wording changes: more idiomatic English
  README.md
Labels: docs
