Repository spaceship-prompt/spaceship-prompt, pull requests merged in 2018-09, with the labels that each got.

#509 Update contribution instructions
  CONTRIBUTING.md
Labels: docs

#430 Use POSIX sed to upgrade version of spaceship
  scripts/version.sh
Labels: bug

#396 Automate GitBook build on push with Travis CI
  .travis.yml
  package.json
Labels: improvement

#340 add `write_perm` func and doc
  docs/Options.md
  sections/dir.zsh
Labels: new-feature
