Repository spaceship-prompt/spaceship-prompt, pull requests merged in 2018-12, with the labels that each got.

#580 Simplify antigen install command
  README.md
Labels: docs, improvement

#582 fix: docker version bug
  sections/docker.zsh
Labels: improvement

#576 Feature for kubecontext section: Custom colors per context/namespace
  docs/Options.md
  sections/kubecontext.zsh
Labels: improvement, review-required

#588 SPACESHIP_KUBECONTEXT_NAMESPACE_SHOW should be empty
  docs/Options.md
  sections/kubecontext.zsh
Labels: improvement, needs doc update, review-required
