Repository spaceship-prompt/spaceship-prompt, pull requests merged in 2019-01, with the labels that each got.

#568 Update README.md
  README.md
Labels: docs

#450 API: Exit section if section variable is empty
  docs/API.md
Labels: docs

#609 Update of hg_branch.zsh
  sections/hg_branch.zsh
Labels: improvement, review-required

#606 Improve pyenv version detection
  sections/pyenv.zsh
Labels: improvement, review-required

#591 Add rules for naming new options
  CONTRIBUTING.md
Labels: docs, improvement, review-required

#597 Truncate conda env names with custom prefix
  docs/Options.md
  sections/conda.zsh
Labels: review-required

#531 Updated docker.zsh to check if a user is in docker container
  sections/docker.zsh
Labels: improvement

#611 fix: go development version
  docs/Options.md
  sections/golang.zsh
Labels: improvement, review-required

#617 Package: Support cargo package manager (Rust)
  docs/Options.md
  sections/package.zsh
Labels: new-feature

#622 Use https in Unicode test scrips and follow redirects
  docs/Troubleshooting.md
Labels: docs
