Repository spaceship-prompt/spaceship-prompt, pull requests merged in 2019-06, with the labels that each got.

#681 Go section detection: Gopkg.yml → Gopkg.toml
  sections/golang.zsh
Labels: improvement

#603 Fix battery_status with acpi
  sections/battery.zsh
Labels: improvement, review-required

#579 Get user environment with spaceship::env
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  scripts/info.sh
  spaceship.zsh
Labels: improvement, needs doc update
