Repository spaceship-prompt/spaceship-prompt, pull requests merged in 2021-06, with the labels that each got.

#944 Migrate docs to mkdocs-material
  .github/workflows/docs.yml
  .github/workflows/main.yaml
  .gitignore
  README.md
  SUMMARY.md
  book.json
  crowdin.yml
  docs/Options.md
  docs/README.md
  docs/api.md
  docs/api.uk.md
  docs/assets/apple-touch-icon.png
  docs/assets/configurable.svg
  docs/assets/favicon.ico
  docs/assets/out-of-the-box.svg
  docs/assets/styles.css
  docs/assets/what-is-needed.svg
  docs/getting-started.md
  docs/getting-started.uk.md
  docs/index.md
  docs/index.uk.md
  docs/options.md
  docs/options.uk.md
  docs/overrides/index.html
  docs/overrides/main.html
  docs/troubleshooting.md
  docs/troubleshooting.uk.md
  logos/spaceship-letters-outlined.svg
  logos/spaceship-letters-outside.svg
  logos/spaceship-no-letters.svg
  mkdocs.yml
  package.json
  requirements.txt
Labels: docs

#952 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: docs

#956 Add semantic release cycle
  .github/workflows/ci.yaml
  .github/workflows/main.yaml
  .releaserc.json
  README.md
  package.json
  scripts/version.sh
Labels: improvement

#957 Fix broken links
  README.md
Labels: docs

#959 New Crowdin updates
  docs/api.uk.md
  docs/getting-started.uk.md
  docs/index.uk.md
  docs/troubleshooting.uk.md
Labels: docs

#964 New Crowdin updates
  docs/api.zh.md
  docs/getting-started.zh.md
  docs/index.zh.md
  docs/options.zh.md
  docs/troubleshooting.zh.md
Labels: translations

#967 New Crowdin updates
  docs/getting-started.zh.md
  docs/index.zh.md
  docs/options.zh.md
Labels: translations

#864 Update ruby asdf version finder
  sections/ruby.zsh
Labels: bug, improvement
