Repository spaceship-prompt/spaceship-prompt, pull requests merged in 2021-02, with the labels that each got.

#838 fix(#837): Hardened the Docker version checking logic
  sections/docker.zsh
  sections/docker_context.zsh
Labels: improvement, sections/docker 🐳

#860 Respect ZDOTDIR env var when looking for .zshrc
  README.md
  scripts/install.sh
  scripts/uninstall.sh
  tests/uninstall.test.zsh
Labels: improvement

#762 Docs: flesh out explanation of custom sections
  README.md
  spaceship.zsh
Labels: docs
