Repository spaceship-prompt/spaceship-prompt, pull requests merged in 2021-07, with the labels that each got.

#1026 New Crowdin updates
  docs/options.uk.md
  docs/options.zh.md
Labels: translations

#1030 Unalias grep for PHP version
  sections/php.zsh
Labels: improvement

#1045 fix: docker section bug and optimize package section
  sections/docker_context.zsh
  sections/package.zsh
Labels: improvement

#1046 fix: get GCLOUD_ACTIVE_CONFIG from ENVIRONMENT, if set
  sections/gcloud.zsh
Labels: improvement

#1053 fix: maven 3.5.0 bug
  sections/maven.zsh
Labels: bug

#1054 Prevent unintended output when `dotnet --version` fails
  sections/dotnet.zsh
Labels: improvement

#1058 Added support for fnm
  README.md
  sections/node.zsh
Labels: new-feature
