Repository spaceship-prompt/spaceship-prompt, pull requests merged in 2022-10, with the labels that each got.

#1249 feat: add Dart section
  docs/config/prompt.md
  docs/registry/internal.json
  docs/sections/dart.md
  mkdocs.yml
  sections/dart.zsh
  spaceship.zsh
  tests/dart.test.zsh
  tests/stubs/dart
Labels: new-feature

#1259 docs(i18n): New Crowdin updates
  docs/config/prompt.de.md
  docs/config/prompt.pl.md
  docs/config/prompt.uk.md
  docs/config/prompt.zh.md
  docs/sections/dart.de.md
  docs/sections/dart.pl.md
  docs/sections/dart.uk.md
  docs/sections/dart.zh.md
  docs/sections/lua.de.md
  docs/sections/lua.pl.md
  docs/sections/lua.uk.md
  docs/sections/lua.zh.md
Labels: docs, translations

#1191 fix(java): fix version retrieval when JAVA_TOOL_OPTIONS exist in environment
  sections/java.zsh
Labels: bug

#1264 docs(i18n): New Crowdin updates
  docs/sections/node.de.md
  docs/sections/node.pl.md
  docs/sections/node.uk.md
  docs/sections/node.zh.md
Labels: docs, translations

#1273 Regonize Apache Ant for java section
  docs/sections/java.md
  sections/java.zsh
Labels: improvement

#1271 docs(i18n): New Crowdin updates
  docs/advanced/creating-section.fr.md
  docs/advanced/per-directory-config.fr.md
  docs/api/environment.fr.md
  docs/api/section.fr.md
  docs/api/testkit.fr.md
  docs/api/utils.fr.md
  docs/config/intro.fr.md
  docs/config/loading-sections.fr.md
  docs/config/prompt.fr.md
  docs/contribute.fr.md
  docs/faq.fr.md
  docs/getting-started.fr.md
  docs/index.fr.md
  docs/registry.fr.md
  docs/sections/async.fr.md
  docs/sections/aws.fr.md
  docs/sections/battery.fr.md
  docs/sections/bun.fr.md
  docs/sections/char.fr.md
  docs/sections/conda.fr.md
  docs/sections/crystal.fr.md
  docs/sections/dart.fr.md
  docs/sections/deno.fr.md
  docs/sections/dir.fr.md
  docs/sections/docker.fr.md
  docs/sections/dotnet.fr.md
  docs/sections/elixir.fr.md
  docs/sections/elm.fr.md
  docs/sections/exec_time.fr.md
  docs/sections/exit_code.fr.md
  docs/sections/gcloud.fr.md
  docs/sections/git.fr.md
  docs/sections/golang.fr.md
  docs/sections/haskell.fr.md
  docs/sections/hg.fr.md
  docs/sections/host.fr.md
  docs/sections/ibmcloud.fr.md
  docs/sections/index.fr.md
  docs/sections/java.fr.md
  docs/sections/jobs.fr.md
  docs/sections/julia.fr.md
  docs/sections/kubectl.fr.md
  docs/sections/line_sep.fr.md
  docs/sections/lua.fr.md
  docs/sections/node.fr.md
  docs/sections/package.fr.md
  docs/sections/php.fr.md
  docs/sections/python.fr.md
  docs/sections/ruby.fr.md
  docs/sections/rust.fr.md
  docs/sections/swift.fr.md
  docs/sections/terraform.fr.md
  docs/sections/time.fr.md
  docs/sections/user.fr.md
  docs/sections/venv.fr.md
  docs/sections/xcode.fr.md
Labels: docs, translations

#1275 Support pyproject.toml for package section
  docs/sections/package.md
  sections/package.zsh
Labels: improvement

#1262 feat: add 'Dart' to the package section
  docs/sections/package.md
  sections/package.zsh
Labels: new-feature

#1261 add reference to external Flutter section
  docs/registry/external.json
Labels: docs

#1248 Added Nix Shell section
  docs/registry/internal.json
  docs/sections/nix_shell.md
  mkdocs.yml
  sections/nix_shell.zsh
  spaceship.zsh
  tests/nix_shell.test.zsh
Labels: new-feature

#1135 perl: Adding perl section to the project
  docs/config/prompt.md
  docs/registry/internal.json
  docs/sections/perl.md
  mkdocs.yml
  sections/perl.zsh
  spaceship.zsh
  tests/perl.test.zsh
  tests/stubs/perl
Labels: new-feature

#1109 Add support for vscode devcontainers to Docker indicator
  sections/docker.zsh
Labels: improvement
