Repository spaceship-prompt/spaceship-prompt, pull requests merged in 2022-12, with the labels that each got.

#1306 Fixing kotlin documentation
  docs/sections/kotlin.md
  mkdocs.yml
Labels: docs

#1301 feat: Add Zig section
  docs/config/prompt.md
  docs/registry/internal.json
  docs/sections/zig.md
  mkdocs.yml
  sections/zig.zsh
  spaceship.zsh
  tests/ansible.test.zsh
  tests/stubs/zig
  tests/zig.test.zsh
Labels: new-feature

#1307 Add PureScript section
  docs/config/prompt.md
  docs/registry/internal.json
  docs/sections/purescript.md
  docs/sections/zig.md
  mkdocs.yml
  sections/purescript.zsh
  spaceship.zsh
  tests/purescript.test.zsh
  tests/stubs/purescript
Labels: new-feature

#1308 Add Erlang section
  docs/config/prompt.md
  docs/registry/internal.json
  docs/sections/erlang.md
  mkdocs.yml
  sections/erlang.zsh
  spaceship.zsh
  tests/erlang.test.zsh
  tests/stubs/erl
Labels: new-feature

#1312 Update README Arch section with maintained release package
  README.md
Labels: improvement
