Repository spaceship-prompt/spaceship-prompt, pull requests merged in 2022-11, with the labels that each got.

#1278 feat(ocaml): Add OCaml section
  docs/config/prompt.md
  docs/registry/internal.json
  docs/sections/ocaml.md
  mkdocs.yml
  sections/ocaml.zsh
  spaceship.zsh
  tests/ocaml.test.zsh
  tests/stubs/ocaml
Labels: new-feature

#1280 Bugfix detect root via version variable
  CONTRIBUTING.md
  spaceship.zsh
Labels: bug, improvement

#1282 feat(docker_compose): Add docker_compose section
  docs/config/prompt.md
  docs/registry/internal.json
  docs/sections/docker_compose.md
  mkdocs.yml
  sections/docker_compose.zsh
  spaceship.zsh
  tests/docker_compose.test.zsh
  tests/stubs/docker-compose
Labels: new-feature

#834 Add pulumi
  docs/config/prompt.md
  docs/registry/internal.json
  docs/sections/pulumi.md
  mkdocs.yml
  sections/pulumi.zsh
  spaceship.zsh
Labels: new-feature

#1283 feat(ansible): Add Ansible section
  docs/config/prompt.md
  docs/registry/internal.json
  docs/sections/ansible.md
  mkdocs.yml
  sections/ansible.zsh
  spaceship.zsh
  tests/ansible.test.zsh
  tests/stubs/ansible
Labels: new-feature

#1062 Add Screen session section to prompt
  docs/config/prompt.md
  docs/sections/gnu_screen.md
  mkdocs.yml
  sections/gnu_screen.zsh
  spaceship.zsh
  tests/gnu_screen.test.zsh
Labels: new-feature

#1289 Added support gradle kotlin dsl
  sections/java.zsh
Labels: improvement
