Repository spaceship-prompt/spaceship-prompt, pull requests merged in 2022-09, with the labels that each got.

#1154 Link the GitHub Sponsors profile
  .github/FUNDING.yml
Labels: docs

#1159 docs: Update Zim installation instructions
  README.md
  docs/getting-started.md
Labels: docs

#1143 feat: Adds asdf support to Elixir version finder
  sections/elixir.zsh
Labels: improvement

#1173 Bun section
  docs/registry/internal.json
  docs/sections/bun.md
  mkdocs.yml
  sections/bun.zsh
  spaceship.zsh
  tests/bun.test.zsh
  tests/stubs/bun
Labels: new-feature

#1183 fix: exec_time doc regarding time threshold trigger
  docs/sections/exec_time.md
Labels: bug

#1189 fix(documentation): use home variable instead of tilde
  README.md
  docs/api/environment.md
  docs/config/intro.md
  docs/getting-started.md
Labels: docs

#1198 docs: update zim installation instructions
  README.md
  docs/getting-started.md
Labels: docs

#1200 docs(i18n): New Crowdin updates
  docs/advanced/creating-section.zh.md
  docs/advanced/per-directory-config.zh.md
  docs/api/environment.zh.md
  docs/api/section.zh.md
  docs/api/testkit.zh.md
  docs/api/utils.zh.md
  docs/config/intro.zh.md
  docs/config/prompt.zh.md
  docs/contribute.zh.md
  docs/faq.zh.md
  docs/getting-started.zh.md
  docs/index.zh.md
  docs/registry.uk.md
  docs/registry.zh.md
  docs/sections/async.zh.md
  docs/sections/aws.zh.md
  docs/sections/battery.zh.md
  docs/sections/bun.zh.md
  docs/sections/char.zh.md
  docs/sections/conda.zh.md
  docs/sections/dir.zh.md
  docs/sections/docker.zh.md
  docs/sections/dotnet.zh.md
  docs/sections/elixir.zh.md
  docs/sections/elm.zh.md
  docs/sections/exec_time.zh.md
  docs/sections/exit_code.zh.md
  docs/sections/gcloud.zh.md
  docs/sections/git.uk.md
  docs/sections/git.zh.md
  docs/sections/golang.zh.md
  docs/sections/haskell.zh.md
  docs/sections/hg.zh.md
  docs/sections/host.zh.md
  docs/sections/ibmcloud.zh.md
  docs/sections/java.zh.md
  docs/sections/julia.zh.md
  docs/sections/kubectl.zh.md
  docs/sections/line_sep.zh.md
  docs/sections/node.zh.md
  docs/sections/package.zh.md
  docs/sections/php.zh.md
  docs/sections/python.zh.md
  docs/sections/ruby.zh.md
  docs/sections/rust.zh.md
  docs/sections/swift.zh.md
  docs/sections/terraform.zh.md
  docs/sections/time.zh.md
  docs/sections/user.zh.md
  docs/sections/venv.zh.md
  docs/sections/xcode.zh.md
Labels: docs, translations

#1205 Delete the redundant space for kubectl symbol (iTerm2)
  docs/sections/kubectl.md
  sections/kubectl.zsh
Labels: improvement

#1209 feat: make package section to support maven and gradle
  docs/sections/package.md
  sections/package.zsh
Labels: new-feature, improvement

#1206 fix: grep unknown option: --color
  lib/utils.zsh
  sections/elixir.zsh
  sections/julia.zsh
  sections/php.zsh
Labels: bug

#1233 docs(i18n): New Crowdin updates
  docs/config/loading-sections.uk.md
  docs/config/prompt.de.md
  docs/config/prompt.pl.md
  docs/config/prompt.uk.md
  docs/config/prompt.zh.md
  docs/getting-started.de.md
  docs/getting-started.pl.md
  docs/getting-started.uk.md
  docs/getting-started.zh.md
  docs/index.de.md
  docs/index.pl.md
  docs/index.uk.md
  docs/index.zh.md
  docs/sections/crystal.de.md
  docs/sections/crystal.pl.md
  docs/sections/crystal.uk.md
  docs/sections/crystal.zh.md
  docs/sections/deno.de.md
  docs/sections/deno.pl.md
  docs/sections/deno.uk.md
  docs/sections/deno.zh.md
  docs/sections/node.de.md
  docs/sections/node.pl.md
  docs/sections/node.uk.md
  docs/sections/node.zh.md
  docs/sections/package.de.md
  docs/sections/package.pl.md
  docs/sections/package.uk.md
  docs/sections/package.zh.md
Labels: docs, translations

#1241 docs(i18n): New Crowdin updates
  docs/faq.zh.md
Labels: docs, translations
